version: '3'

services:
  database:
    build:
      context: ./mongoDocker/
    container_name: database
    ports:
      - "27012:27017"
    networks:
      - mongo-network
    volumes:
      - mongodb-data:/data/db

  fer_model:
    build:
      context: ./models/
    container_name: fer_model
    ports:
      - "8080:8080"
    networks:
      - mongo-network

volumes:
  mongodb-data:

networks:
  mongo-network: