# Use the official MongoDB image
FROM mongo:latest

# Expose the MongoDB port
EXPOSE 27012

# Optionally, add any MongoDB initialization scripts if needed
# COPY init-mongo.js /docker-entrypoint-initdb.d/